AZURE_BLOB_CONNECTION_STRING = "DefaultEndpointsProtocol=https;AccountName=wiskiblob;AccountKey=LZ+d4MzoG8ll7um64uh8SGIr1uK/iMmNx+PnYC8zPvaO4zzi0qW9QxBPQtR0374K7yWvNf+uOT8U+AStA7GG6A==;EndpointSuffix=core.windows.net"
AZURE_BLOB_CONTAINER_NAME = "wiski-container"
AZURE_SEARCH_SERVICE_NAME = "ai-search-wiski"
AZURE_SEARCH_INDEX_NAME = "test-index-1-store"
AZURE_SEARCH_ADMIN_KEY = "Zu8iq9PKbNIuSpiroRCrmwWZK7hoE1hMNIrGB6ATinAzSeBBG0KC"
APP_USERNAME = "1"
APP_PASSWORD = "2"